import type { UserRole } from "@/types";

const ALL: UserRole[] = ["viewer", "editor", "admin", "super_admin"];

export const SEED_CATEGORIES = [
  {
    name: "Daily Work",
    slug: "daily-work",
    description: "Everyday tools and communication",
    order: 1,
    isActive: true,
  },
  {
    name: "Intake",
    slug: "intake",
    description: "Client intake and lead management",
    order: 2,
    isActive: true,
  },
  {
    name: "Case Management",
    slug: "case-management",
    description: "Case tracking and workflow tools",
    order: 3,
    isActive: true,
  },
  {
    name: "Training",
    slug: "training",
    description: "Onboarding and learning resources",
    order: 4,
    isActive: true,
  },
  {
    name: "Marketing",
    slug: "marketing",
    description: "Brand, social, and web presence",
    order: 5,
    isActive: true,
  },
  {
    name: "Admin",
    slug: "admin",
    description: "Internal operations and settings",
    order: 6,
    isActive: true,
  },
] as const;

export function getSeedCards(categorySlug: string) {
  const cards = [
    {
      title: "Team Directory",
      description: "Find colleagues, roles, and contact info",
      icon: "directory",
      categoryId: "daily-work",
      type: "internal_tool" as const,
      url: "/directory",
      tags: ["people", "directory", "team"],
      visibilityRoles: ALL,
      isActive: true,
      isNew: true,
      isImportant: false,
      order: 0,
    },
    {
      title: "Slack",
      description: "Team messaging and channels",
      icon: "slack",
      categoryId: "daily-work",
      type: "external_link" as const,
      url: "https://slack.com",
      tags: ["communication", "chat"],
      visibilityRoles: ALL,
      isActive: true,
      isNew: false,
      isImportant: true,
      order: 1,
    },
    {
      title: "Dropbox",
      description: "Shared files and document storage",
      icon: "dropbox",
      categoryId: "daily-work",
      type: "external_link" as const,
      url: "https://www.dropbox.com",
      tags: ["files", "storage"],
      visibilityRoles: ALL,
      isActive: true,
      isNew: false,
      isImportant: false,
      order: 2,
    },
    {
      title: "Google Drive",
      description: "Firm documents and shared drives",
      icon: "google-drive",
      categoryId: "daily-work",
      type: "external_link" as const,
      url: "https://drive.google.com",
      tags: ["files", "google"],
      visibilityRoles: ALL,
      isActive: true,
      isNew: false,
      isImportant: true,
      order: 3,
    },
    {
      title: "DocketFlow",
      description: "Case workflow and docket management",
      icon: "docketflow",
      categoryId: "case-management",
      type: "dashboard" as const,
      url: "#",
      tags: ["cases", "workflow"],
      visibilityRoles: ["editor", "admin", "super_admin"] as UserRole[],
      isActive: true,
      isNew: true,
      isImportant: true,
      order: 1,
    },
    {
      title: "Quo",
      description: "Client communication platform",
      icon: "quo",
      categoryId: "intake",
      type: "external_link" as const,
      url: "#",
      tags: ["intake", "communication"],
      visibilityRoles: ALL,
      isActive: true,
      isNew: false,
      isImportant: false,
      order: 1,
    },
    {
      title: "CallRail",
      description: "Call tracking and attribution",
      icon: "callrail",
      categoryId: "intake",
      type: "external_link" as const,
      url: "https://www.callrail.com",
      tags: ["calls", "marketing"],
      visibilityRoles: ["editor", "admin", "super_admin"] as UserRole[],
      isActive: true,
      isNew: false,
      isImportant: false,
      order: 2,
    },
    {
      title: "Adobe Sign / DocuSeal",
      description: "E-signatures and document execution",
      icon: "adobe-sign",
      categoryId: "case-management",
      type: "document" as const,
      url: "#",
      tags: ["signatures", "documents"],
      visibilityRoles: ALL,
      isActive: true,
      isNew: false,
      isImportant: false,
      order: 2,
    },
    {
      title: "New Hire Training",
      description: "Onboarding modules for new team members",
      icon: "training",
      categoryId: "training",
      type: "training" as const,
      url: "/training/new-hire",
      tags: ["onboarding", "hr"],
      visibilityRoles: ALL,
      isActive: true,
      isNew: true,
      isImportant: true,
      order: 1,
    },
    {
      title: "SOP Library",
      description: "Standard operating procedures and playbooks",
      icon: "sop-library",
      categoryId: "training",
      type: "document" as const,
      url: "#",
      tags: ["sops", "process"],
      visibilityRoles: ALL,
      isActive: true,
      isNew: false,
      isImportant: false,
      order: 2,
    },
    {
      title: "Case Tracker",
      description: "Internal case status overview",
      icon: "case-tracker",
      categoryId: "case-management",
      type: "internal_tool" as const,
      url: "#",
      tags: ["cases"],
      visibilityRoles: ["editor", "admin", "super_admin"] as UserRole[],
      isActive: true,
      isNew: false,
      isImportant: true,
      order: 3,
    },
    {
      title: "Website Admin",
      description: "Firm website content management",
      icon: "website-admin",
      categoryId: "marketing",
      type: "internal_tool" as const,
      url: "#",
      tags: ["web", "cms"],
      visibilityRoles: ["admin", "super_admin"] as UserRole[],
      isActive: true,
      isNew: false,
      isImportant: false,
      order: 1,
    },
    {
      title: "Social Media Accounts",
      description: "Linked accounts and posting tools",
      icon: "social-media",
      categoryId: "marketing",
      type: "external_link" as const,
      url: "#",
      tags: ["social", "marketing"],
      visibilityRoles: ["editor", "admin", "super_admin"] as UserRole[],
      isActive: true,
      isNew: false,
      isImportant: false,
      order: 2,
    },
    {
      title: "Google Business Profile",
      description: "Reviews, listings, and local SEO",
      icon: "google-business",
      categoryId: "marketing",
      type: "external_link" as const,
      url: "https://business.google.com",
      tags: ["seo", "reviews"],
      visibilityRoles: ["editor", "admin", "super_admin"] as UserRole[],
      isActive: true,
      isNew: false,
      isImportant: false,
      order: 3,
    },
  ];

  return cards.map((c) => ({
    ...c,
    categoryId: categorySlug === "all" ? c.categoryId : c.categoryId,
  }));
}

export const SEED_CARDS = getSeedCards("all");
